# Client Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetsudoeki-client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tetsudoeki-client
  template:
    metadata:
      labels:
        app: tetsudoeki-client
    spec:
      containers:
        - name: tetsudoeki-client
          image: evantyip/tetsudoeki-client
---
apiVersion: v1
kind: Service
metadata:
  name: tetsudoeki-client-srv
spec:
  selector:
    app: tetsudoeki-client
  ports:
    - name: tetsudoeki-client
      protocol: TCP
      port: 3000
      targetPort: 3000
