name: deploy-completed
on:
  push:
    branches:
      - master
    paths:
      - 'completed/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd completed && docker build -t evantyip/tetsudoeki-completed .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push evantyip/tetsudoeki-completed
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save tetsudo-eki
      - run: kubectl rollout restart deployment tetsudoeki-completed-depl
