name: deploy-watching
on:
  push:
    branches:
      - master
    paths:
      - 'watching/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd watching && docker build -t evantyip/tetsudoeki-watching .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push evantyip/tetsudoeki-watching
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save tetsudo-eki
      - run: kubectl rollout restart deployment tetsudoeki-watching-depl
