# testing
name: test-discover

on:
  pull_request:
    paths:
      - 'discover/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd discover && npm install && npm run test:ci
